# Generated by Django 3.2.14 on 2022-11-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteABS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_abs', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_abs', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email_abs', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni_abs', models.IntegerField(verbose_name='DNI')),
                ('matricula_abs', models.CharField(max_length=10, verbose_name='Matricula')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
